### PR TITLE
Add meson build config

### PR DESCRIPTION
**Pull request by franko**
Add a meson build config alongside to the cmake config.

The new meson config is supposed to be on par with the cmake one. I tested on Windows and Linux and it appear to works.

### Why a meson config ?

Meson is a modern free software build system widely used in many free software projects like Mesa 3D, Gnome and many others.

Compared to a cmake config meson is less obscure and complicated and some people may prefer it. Maintaining a meson build alongside the cmake one should be easy as the meson config is very simple.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Meson has support for CMake built-in, see https://mesonbuild.com/CMake-module.html. This should be sufficient to use reproc from meson, correct? I tested a while ago that this works as expected.

> Compared to a cmake config meson is less obscure and complicated and some people may prefer it. Maintaining a meson build alongside the cmake one should be easy as the meson config is very simple.

If you take someone completely unfamiliar with both, I agree that meson is probably more understandable. Unfortunately, CMake is the defacto standard in C++. Given that meson has been so kind to implement extensive CMake support,, I'd much prefer sticking with just CMake.

Let me know if writing our own meson config has advantages over relying on meson's built-in CMake support. If it doesn't offer any substantial advantages, I'd prefer to stick with just CMake.

**Comment by franko** [comment]
Thank you for taking the time to look at my PR.

> Meson has support for CMake built-in, see https://mesonbuild.com/CMake-module.html. This should be sufficient to use reproc from meson, correct? I tested a while ago that this works as expected.

Well, Meson has support to discover cmake based libraries but cmake is not supported for subprojects. More information there:

https://mesonbuild.com/Subprojects.html

> If you take someone completely unfamiliar with both, I agree that meson is probably more understandable. Unfortunately, CMake is the defacto standard in C++. Given that meson has been so kind to implement extensive CMake support,, I'd much prefer sticking with just CMake.

I have the impression in your argument there you are mixing different things. Let break them down.

> If you take someone completely unfamiliar with both, I agree that meson is probably more understandable.

If you look at any moderately sized project you will see that the cmake config is wildly complicated and difficult to understand for anybody. It is not just a matter of being familiar or not with cmake. Meson manages to stay more reasonable in term of complexity while supporting large and complicated projects. Most people agree about that even when they choose to stay with cmake.

> Unfortunately, CMake is the defacto standard in C++.

This is sort of true, I agree, but there are also many projects using Meson. We may also decide the technologies we use based on their merits.

> Let me know if writing our own meson config has advantages over relying on meson's built-in CMake support. If it doesn't offer any substantial advantages, I'd prefer to stick with just CMake.

As I wrote above I need a meson config to integrate reproc as a subproject and it would be nice to have the meson config integrated upstream. If you prefer to stick with CMake that's fine but you may still merge the meson config.

**Comment by DaanDeMeyer** [comment]
https://mesonbuild.com/CMake-module.html#cmake-subprojects

Are you sure you read the page correctly? Maybe I'm missing something, but the page I linked shows how to use a CMake project as a meson subproject. This should work as expected. If it doesn't I'm happy to make the necessary changes to reproc's CMake config files to make it work as a meson subproject.

**Comment by franko** [comment]
> Are you sure you read the page correctly? Maybe I'm missing something, but the page I linked shows how to use a CMake project as a meson subproject.

Well they actually say: "CMake based subprojects are also supported but not guaranteed to work" so you are right but I am not very comfortable with that.

> This should work as expected. If it doesn't I'm happy to make the necessary changes to reproc's CMake config files to make it work as a meson subproject.

Ok, in this case feel free to close this PR.

There are many versions of Meson and Cmake around, I am not going to have fun testing all the possible combinations. In addition I don't like to depend on both Meson and cmake for my project.

**Comment by DaanDeMeyer** [comment]
Let's close this then.

**Pull request closed without merging**
