### PR TITLE
Add `REPROC_ENV_EXTEND_MERGE`

### PR DESCRIPTION
**Pull request by dr-doodong**
I wasn't able to run the clang-format so the code style is little bit of inconsistent as it is.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
We should not implement the merging twice. I would implement a platform specific function to get the environment in a common format, let's say a strv., do the merge in the shared code, and pass the final result back to the process start function. That way we only have to implement the merge once.

**Review by DaanDeMeyer — CHANGES_REQUESTED** [review]
We should not implement the merging twice. I would implement a platform specific function to get the environment in a common format, let's say a strv., do the merge in the shared code, and pass the final result back to the process start function. That way we only have to implement the merge once.

**Comment by rankaisija64** [comment]
> We should not implement the merging twice. I would implement a platform specific function to get the environment in a common format, let's say a strv., do the merge in the shared code, and pass the final result back to the process start function. That way we only have to implement the merge once.

So one function with a bunch of preprocessor guards going on or something? I'm not so fluent with programming talk so I have hard time following what you mean.

**Comment by DaanDeMeyer** [comment]
> So one function with a bunch of preprocessor guards going on or something? I'm not so fluent with programming talk so I have hard time following what you mean.

No, one function without any ifdeffery using just standard C that takes two arrays of strings and merges them

**Comment by rankaisija64** [comment]
I'll see what I can do

**Comment by DaanDeMeyer** [comment]
Closing due to lack of update

**Pull request closed without merging**
